services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      retries: 10
  data-fetcher-svc:
    image: onurozguzel/data-fetcher-svc:latest
    build:
      context: .
      dockerfile: src/RickAndMortyDataFetcher/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Docker
    depends_on:
      postgres:
        condition: service_healthy
  web-app-svc:
    image: onurozguzel/web-app-svc:latest
    build:
      context: .
      dockerfile: src/RickAndMortyWebApp/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Docker
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
      data-fetcher-svc:
        condition: service_completed_successfully
volumes:
  pgdata: